-- MySQL Script generated by MySQL Workbench
-- Sat May 29 23:15:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TEST
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TEST` ;

-- -----------------------------------------------------
-- Schema TEST
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TEST` DEFAULT CHARACTER SET utf8 ;
USE `TEST` ;

-- -----------------------------------------------------
-- Table `TEST`.`POKEMONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEST`.`POKEMONS` ;

CREATE TABLE IF NOT EXISTS `TEST`.`POKEMONS` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `version_group` varchar(50) NOT NULL,
  `is_mega` tinyint(1) DEFAULT NULL,
  `is_default` tinyint(1) DEFAULT NULL,
  `is_battle_only` tinyint(1) DEFAULT NULL,
  `type` varchar(45) DEFAULT NULL,
  `ability` varchar(45) DEFAULT NULL,
  `strength` varchar(45) DEFAULT NULL,
  `moves` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `SKU_UNIQUE` (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
